library(lubridate)
temp <- tempfile()  #Download the file and read only the text file from the zipped folder
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", temp)
hhpc <- read.delim(unz(temp,"household_power_consumption.txt"),header= TRUE, sep=";") 
unlink(temp)
hhpc <-  hhpc[(hhpc$Date=="1/2/2007") | (hhpc$Date =="2/2/2007" ),]
hhpc$tme <- dmy_hms(paste(hhpc$Date, " ", hhpc$Time))
hhpc$Sub_metering_1 <- as.numeric(hhpc$Sub_metering_1)
hhpc$Sub_metering_2 <- as.numeric(hhpc$Sub_metering_2)
hhpc$Sub_metering_3 <- as.numeric(hhpc$Sub_metering_3)
hhpc$Global_active_power<- as.numeric(hhpc$Global_active_power)
hhpc$Global_reactive_power<- as.numeric(hhpc$Global_reactive_power)
hhpc$Voltage <- as.numeric(hhpc$Voltage)
par(mfrow=c(2,2),mar=c(4,4,1,1))
plot(x=hhpc$tme ,y=hhpc$Global_active_power,type ="l", ylab="Global Active Power", xlab = "")
plot(x=hhpc$tme ,y=hhpc$Voltage,type ="l", ylab="Voltage", xlab = "datetime")
plot(x=hhpc$tme ,y=hhpc$Sub_metering_1, type = "l", col="black", ylab = "Energy sub metering", xlab="")
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_2,type ="l",col="blue"))
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_2,type ="l",col="red"))
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_3,type ="l",col="blue"))
legend("topright", lty=1, col = c("black" ,"red", "blue"),bty = "n",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(x=hhpc$tme ,y=hhpc$Global_reactive_power,type ="l", ylab="Global_reactive_power", xlab = "datetime", ylim = c(0,0.5))
dev.copy(png,"Plot4.png")
dev.off()
