library(lubridate)
hhpc <- read.delim("household_power_consumption.txt",header= TRUE, sep=";")
hhpc <-  hhpc[(hhpc$Date=="1/2/2007") | (hhpc$Date =="2/2/2007" ),]
hhpc$tme <- dmy_hms(paste(hhpc$Date, " ", hhpc$Time))
hhpc$Sub_metering_1 <- as.numeric(hhpc$Sub_metering_1)
hhpc$Sub_metering_2 <- as.numeric(hhpc$Sub_metering_2)
hhpc$Sub_metering_3 <- as.numeric(hhpc$Sub_metering_3)
plot(x=hhpc$tme ,y=hhpc$Sub_metering_1, type = "l", col="black", ylab = "Energy sub metering", xlab="")
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_2,type ="l",col="blue"))
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_2,type ="l",col="red"))
with(hhpc,lines(x=hhpc$tme ,y=hhpc$Sub_metering_3,type ="l",col="blue"))
legend("topright", lty=1, col = c("black" ,"red", "blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,"Plot3.png")
dev.off()
